namespace Windows.Image
{
    public enum SYM_STORAGE_CLASS : byte
    {
        IMAGE_SYM_CLASS_NULL = 0,

        IMAGE_SYM_CLASS_AUTOMATIC = 1,

        IMAGE_SYM_CLASS_EXTERNAL = 2,

        IMAGE_SYM_CLASS_STATIC = 3,

        IMAGE_SYM_CLASS_REGISTER = 4,

        IMAGE_SYM_CLASS_EXTERNAL_DEF = 5,

        IMAGE_SYM_CLASS_LABEL = 6,

        IMAGE_SYM_CLASS_UNDEFINED_LABEL = 7,

        IMAGE_SYM_CLASS_MEMBER_OF_STRUCT = 8,

        IMAGE_SYM_CLASS_ARGUMENT = 9,

        IMAGE_SYM_CLASS_STRUCT_TAG = 10,

        IMAGE_SYM_CLASS_MEMBER_OF_UNION = 11,

        IMAGE_SYM_CLASS_UNION_TAG = 12,

        IMAGE_SYM_CLASS_TYPE_DEFINITION = 13,

        IMAGE_SYM_CLASS_UNDEFINED_STATIC = 14,

        IMAGE_SYM_CLASS_ENUM_TAG = 15,

        IMAGE_SYM_CLASS_MEMBER_OF_ENUM = 16,

        IMAGE_SYM_CLASS_REGISTER_PARAM = 17,

        IMAGE_SYM_CLASS_BIT_FIELD = 18,

        IMAGE_SYM_CLASS_BLOCK = 100,

        IMAGE_SYM_CLASS_FUNCTION = 101,

        IMAGE_SYM_CLASS_END_OF_STRUCT = 102,

        IMAGE_SYM_CLASS_FILE = 103,

        IMAGE_SYM_CLASS_SECTION = 104,

        IMAGE_SYM_CLASS_WEAK_EXTERNAL = 105,

        IMAGE_SYM_CLASS_CLR_TOKEN = 107,

        IMAGE_SYM_CLASS_END_OF_FUNCTION = 255,
    }
}