//-----------------------------------------------------------------------------
// Copyright   :  (c) Chris Moore, 2020
// License     :  MIT
//-----------------------------------------------------------------------------
namespace Z0
{
    using static FileKindNames;

    [SymSource("files")]
    public enum FileKind : uint
    {
        None = 0,

        [Symbol(asm,"Formatted x86 assembly")]
        Asm,

        [Symbol(encodingasm, "An asm file that contains the encoding as comments")]
        EncodingAsm,

        [Symbol(synasm)]
        AsmSyntax,

        [Symbol(synasmlog)]
        AsmSyntaxLog,

        [Symbol(bat, "A windows batch file")]
        Bat,

        [Symbol(bc, "An llvm-ir binary file")]
        Bc,

        [Symbol(bin, "A flat binary file")]
        Bin,

        [Symbol("bits", "A bitfield specification")]
        Bits,

        [Symbol(i, "A file generated by a pre-processor for a c translation unit")]
        Ci,

        [Symbol(ii, "A file generated by a pre-processor for a cpp translation unit")]
        Cii,

        [Symbol(cil, "Msil source text")]
        Cil,

        [Symbol(cmd, "A windows batch file")]
        Cmd,

        [Symbol(c, "A c source file")]
        C,

        [Symbol(coffheaders, "A file containing a textual description of the headers in a COFF object file")]
        CoffHeaders,

        [Symbol(cpp, "A cpp source file")]
        Cpp,

        [Symbol(csv,"Delimited data rows")]
        Csv,

        [Symbol(cs, "A csharp source file")]
        Cs,

        [Symbol(csproj, "A CSharp project file")]
        CsProj,

        [Symbol(dmp, "A windows dump file")]
        Dmp,

        [Symbol(dll, "A dynamic library module")]
        Dll,

        [Symbol(exe, "A portable executable file")]
        Exe,

        [Symbol(hex, "Text-formatted hex data")]
        Hex,

        [Symbol(hexdat)]
        HexDat,

        [Symbol(ildata, "MSIL organized in tabular format")]
        IlData,

        [Symbol(json, "Json data")]
        Json,

        [Symbol(lib, "A static library module")]
        Lib,

        [Symbol(llasm, "An asm file produced by llc")]
        LlAsm,

        [Symbol(ll, "An llvm-ir text file")]
        Llir,

        [Symbol(log,"Text-formatted log data")]
        Log,

        [Symbol(o, "A coff object file")]
        O,

        [Symbol(obi, "A textual description of acoff object file as produced by llvm-readobj")]
        Obi,

        [Symbol(obj, "A coff object file")]
        Obj,

        [Symbol(objasm, "An assembly file derived from an object file")]
        ObjAsm,

        [Symbol(pcsv,"Text-formatted x86-encoded/executable data")]
        PCsv,

        [Symbol(h, "A C/C++ header file")]
        H,

        [Symbol(mcasm, "An asm file produced by the llvm-mc tool")]
        McAsm,

        [Symbol(objyaml)]
        ObjYaml,

        [Symbol(sym,"A symbol table as emitted by llvm-nm")]
        Sym,

        [Symbol(sql, "A sql script")]
        Sql,

        [Symbol(txt,"Text data")]
        Txt,

        [Symbol(mlir)]
        Mlir,

        [Symbol(mir)]
        Mir,

        [Symbol(xcsv,"Unprocessed x86-encoded data")]
        XCsv,

        [Symbol(xpack, "Text-formatted hex with base addresses")]
        XPack,

        [Symbol(xml, "Xml data")]
        Xml,

        [Symbol(yamltok)]
        YamlTok,

        [Symbol(xeddisasm_raw, "Xed disassembly information as emitted from the xed tool")]
        XedRawDisasm,

        [Symbol(xeddisasm_summary, "Xed disassembly tabular summary")]
        XedSummaryDisasm,

        [Symbol(xeddisasm_semantic, "Xed disassembly details with semantic interpretation")]
        XedSemanticDisasm,

        [Symbol("ll.bc")]
        LlBc,

        [Symbol("s")]
        S,
    }
}