@echo off
call %SlnDeprecatedCmd%
call %SlnExprCmd%
call %SlnLangCmd%
call %SlnExtractCmd%
call %SlnRulesCmd%
call %SlnGlueCmd%
call %SlnLlvmToolsCmd%
call %SlnAllocCmd%
call %SlnApiCodeCmd%
call %SlnArchivesCmd%
call %SlnAssetsCmd%
call %SlnBitsCmd%
call %SlnCommandsCmd%
call %SlnSymbolsCmd%
call %SlnNumbersCmd%
call %SlnDiagnosticsCmd%
call %SlnAsmOperandsCmd%
call %SlnAsmCoreCmd%
call %SlnIntelCoreCmd%
call %SlnIntelIntrinsicsCmd%
call %SlnIntelXedCmd%
call %SlnCmdActionsCmd%
call %SlnAsmPrototypesCmd%
call %SlnAsmServicesCmd%
call %SlnAsmCmd%
call %SlnMachinesCmd%
call %SlnCgIntelCmd%
call %SlnCgCommonCmd%
call %SlnCgLlvmCmd%
call %SlnApiMd%
